server:
  port: 8085

spring:
  data:
    redis:
      host: localhost
      port: 6379
  application:
    name: api-gateway


  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:

            - id: user-service-auth
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/auth/**
              filters:
                - AddRequestHeader=X-Gateway-Request, RestaurantGateway
                - AddResponseHeader=X-Gateway-Response, RoutedByGateway

            - id: user-service-users
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/users/**
              filters:
                - AddRequestHeader=X-Gateway-Request, RestaurantGateway
                - AddResponseHeader=X-Gateway-Response, RoutedByGateway

            - id: categories
              uri: lb://RESTAURANTAPP
              predicates:
                - Path=/api/categories/**
              filters:
                - AddRequestHeader=X-Gateway-Request, RestaurantGateway
                - AddResponseHeader=X-Gateway-Response, RoutedByGateway

            - id: menu-items
              uri: lb://RESTAURANTAPP
              predicates:
                - Path=/api/menu-items/**
              filters:
                - AddRequestHeader=X-Gateway-Request, RestaurantGateway
                - AddResponseHeader=X-Gateway-Response, RoutedByGateway

            - id: orders
              uri: lb://RESTAURANTAPP
              predicates:
                - Path=/api/orders/**
              filters:
                - AddRequestHeader=X-Gateway-Request, RestaurantGateway
                - AddResponseHeader=X-Gateway-Response, RoutedByGateway

            - id: order-items
              uri: lb://RESTAURANTAPP
              predicates:
                - Path=/api/order-items/**
              filters:
                - AddRequestHeader=X-Gateway-Request, RestaurantGateway
                - AddResponseHeader=X-Gateway-Response, RoutedByGateway

            - id: payments
              uri: lb://RESTAURANTAPP
              predicates:
                - Path=/api/payments/**
              filters:
                - AddRequestHeader=X-Gateway-Request, RestaurantGateway
                - AddResponseHeader=X-Gateway-Response, RoutedByGateway

            - id: restaurant-tables
              uri: lb://RESTAURANTAPP
              predicates:
                - Path=/api/restaurant-tables/**
              filters:
                - AddRequestHeader=X-Gateway-Request, RestaurantGateway
                - AddResponseHeader=X-Gateway-Response, RoutedByGateway

            - id: reporting-service
              uri: lb://REPORTING-SERVICE
              predicates:
                - Path=/api/reports/**
              filters:
                - AddRequestHeader=X-Gateway-Request, RestaurantGateway
                - AddResponseHeader=X-Gateway-Response, RoutedByGateway

                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 5
                    redis-rate-limiter.burstCapacity: 10
                    key-resolver: "#{@ipKeyResolver}"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,prometheus
  endpoint:
    health:
      show-details: always